# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4kGix2YMXklVabAVstDk33Mbl57dgEI

Sentiment Analysis
"""

def search(SEARCH_WORDS,DATE_SINCE,NBR_TWEETS):
  '''
  This is a function is to search Tweets and store them in Df
  Inputs: SEARCH_WORDS, DATE_SINCE and NBR_TWEETS
  Output: the dataframe resulting the search. 
  '''
  auth = tw.OAuthHandler(CONSUMER_KEY,CONSUMER_SECRET)
  auth.set_access_token(ACCESS_TOKEN,ACCESS_TOKEN_SECRET)
  api = tw.API(auth,wait_on_rate_limit= True)
  search = tw.Cursor(api.search,
                    q= SEARCH_WORDS + '-filter:retweets',
                     lang='en',).items(NBR_TWEETS)

  time_tweet = [[tweet.created_at,tweet.text] for tweet in search]
  df_tweets = pd.DataFrame(data=time_tweet,
                           columns=['time','tweet'])
  return df_tweets

def compute_sentiment_value(df):
  '''
  This is a function is made for Data Analysis. It counts the occurence of keywords in the tweets and return a value between -100% and +100%.
  Inputs: previous dataframe.
  Output: a value between -100% and +100% 
  '''
  sentiment_value = 0

  for i in range(len(df)):
    for keywords in POSITIVE_KEYWORDS: 
      sentiment_value += df['tweet'][i].count(keywords)
      for keywords in NEGATIVE_KEYWORDS:
          sentiment_value -= df['tweet'][i].count(keywords)
  return sentiment_value


def sentiment_value_filter(sentiment_value):
  '''
  This is a function that takes the value 1 if sentiment > 10% , -1 if sentiment < -10%, else = 0
  Inputs: the previous sentiment value. 
  Output: 0 or 1.
  '''
  if sentiment_value > 0.01:
    sentiment_filter = 1
  elif sentiment_value < -0.01:
    sentiment_filter = -1
  else:
     sentiment_filter = 0 
  return sentiment_filter


def sentiment_evolution(df):
  '''
  This is a function that counts the keywords in each row of the df and create a new df to store the count row by row
  Inputs: the previous df
  Output: a df_reverted
  '''
  df_copy = df.copy()
  df_reverted = df_copy.sort_index(axis=1 ,ascending=True)
  counter = 0
  for i in range(len(df_reverted)):
    counter = 0
    for keywords in POSITIVE_KEYWORDS:
       counter += df_reverted['tweet'][i].count(keywords)
    for keywords in NEGATIVE_KEYWORDS:
       counter -= df_reverted['tweet'][i].count(keywords)

    df_reverted['tweet'][i] = counter 
  df_reverted.columns = ['time','sentiment']
#rename the col
  return df_reverted

"""Trading Analysis"""

def PlotPy(TICKER, PERIOD, INTERVAL):
    '''
    This is a function made for plotting purposes for the MA trading strategy ONLY.
    Inputs: TICKER, START, END
    Output: a plot
    '''
    price = yfinance.download(tickers =TICKER,period = PERIOD, interval=INTERVAL)

    fig = plt.figure()

    ax1 = fig.add_subplot(111, ylabel = 'Price')

    # Plot the closing prices
    ticker_data['Close'].plot(ax=ax1, color = 'b', lw=2)

    # Plot the short and long moving average
    signals[['short_mavg','long_mavg']].plot(ax=ax1, lw=2)

    # Plot the buy signal
    ax1.plot(signals.loc[signals.position == 1.0].index, signals.short_mavg[signals.position == 1.0], marker = '^', markersize = 10, color='g', lw=0)

    # Plot the sell signal
    ax1.plot(signals.loc[signals.position == -1.0].index,signals.short_mavg[signals.position == -1.0], marker = 'v', markersize = 10, color='r', lw=0)

    ax1.legend(loc='best')   
    ax1.grid(axis = "both", linestyle = '--')
    plt.title('AVAX-USD MA-Cross Over Strategy', fontsize = 15)

    plt.show()
    print("Note : This Graph shows the MA strategy whitout the sentiment analysis trading strategy")

def strategy(signal_value, sentiment_filter): 
    '''
    This function creates the MA + Sentiment Analysis trading strategy.
    Inputs: signal position
            sentiment filter
    Output: the results of the trading strategy.
    '''

    if signal_value == 1 & sentiment_filter == 1:
       print('\x1b[5;32;47m' + "Cross of MA + Positive Market Sentiment = Buy" + '\x1b[0m')
    if signal_value == 1 & sentiment_filter == 0:
      print("Cross of MA + Neutral Market Sentiment : Analyse more thorougly what is happening in the market")
    if signal_value == 1 & sentiment_filter == -1:
      print("Cross of MA + Negative Market Sentiment : Analyse more thorougly what is happening in the market")

    if signal_value == 0 & sentiment_filter == 1:
      print("No Cross of MA + Positive Market Sentiment : Analyse more thorougly what is happening in the market")
    if signal_value == 0 & sentiment_filter == 0:
      print("No cross of MA + Neutral Market Sentiment :Analyse more thorougly what is happening in the market")
    if signal_value == 0 & sentiment_filter == -1:
      print('\x1b[5;31;47m' + "No cross of MA + Negative Market Sentiment : Short" + '\x1b[0m')