# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4kGix2YMXklVabAVstDk33Mbl57dgEI
"""

#Librairies
import pandas as pd
import tweepy as tw
from pandas_datareader import data
import matplotlib.pyplot as plt
import numpy as np
import datetime
import plotly
import yfinance

#API Keys
CONSUMER_KEY = 'S9eO1ZKwGW0zuF4SK71fhoine'
CONSUMER_SECRET = 'EeH5TbJvfIe0VgzY6AQxJmdg5SBzLp1rFSfGnUkqCLZxbFxuya'
ACCESS_TOKEN = '1359884187373883402-6q5YcNr0AVwLlF9x1ZXzdTQiPA9vwO'
ACCESS_TOKEN_SECRET = '6ZHO43NGQUx1IGwdnbChpsRP1TEhKNYkShnsCrTvc3doh'

# Define the search term and the DATE_SINCE date as variables
SEARCH_WORDS = "#avax"
DATE_SINCE = "2020-02-14"
NBR_TWEETS = 1000

#Define Positive and Negative keywords to look for
POSITIVE_KEYWORDS = ['buy','long','pump','up','invest','enter','bull','bullish','bottom']
NEGATIVE_KEYWORDS = ['sell','short','dump','down','scam','exit','bear','bearish','top']

 #Define the main variables in the trading strategy
TICKER = 'AVAX-USD'
START = '2021-01-01'
END = '2021-03-01'
SHORT_LOOKBACK_PERIOD = 50
LONG_LOOKBACK_PERIOD = 200
INITIAL_CAPITAL = 10000
NBRE_SHARES = 100
PERIOD = "5d"
INTERVAL="1h"