# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4kGix2YMXklVabAVstDk33Mbl57dgEI
"""

#Initialize API & Store tweets in a Dataframe
df_tweets = search(SEARCH_WORDS,DATE_SINCE,NBR_TWEETS)

#Sentiment Analysis

#Count the number of positive/negative keywords in tweets and return a value between -100% & +100% to indicate sentiment
sentiment_value = compute_sentiment_value(df_tweets) 

# Give trading signal: 1 for long if sentiment_value > +10% | -1 For short if sentiment < -10% | 0 for neutral 
sentiment_filter = sentiment_value_filter(sentiment_value) 

#Create a new df with sentiment variation stored in each row
df_sentiment_evolution = sentiment_evolution(df_tweets)  

#Plot graph
fig = plotly.express.histogram(df_sentiment_evolution,x='time', y='sentiment',nbins = 60, title='Variation in Sentiment') 

#Show graph
fig.show()

#SETUPS
ticker_data = yfinance.download(tickers ='AVAX-USD',period = "5d", interval="60m")

# Prepare a signal dataframe with Date same as from TICKER data
signals = pd.DataFrame(index=ticker_data.index)
signals['signal'] = 0.0

# Short moving average
signals['short_mavg'] = ticker_data['Close'].rolling(window=SHORT_LOOKBACK_PERIOD, min_periods=1, center=False).mean()

# Long moving average
signals['long_mavg'] = ticker_data['Close'].rolling(window=LONG_LOOKBACK_PERIOD, min_periods = 1, center=False).mean()

# Identify cross overs : when short moving avg is greater than long moving average
# Value 1 if True, Value 0 if False
signals['signal'][SHORT_LOOKBACK_PERIOD:] = np.where(signals['short_mavg'][SHORT_LOOKBACK_PERIOD:] > signals['long_mavg'][SHORT_LOOKBACK_PERIOD:], 1.0, 0.0) 

signals['position'] = signals['signal'].diff()

signal_value = signals.position.iloc[-1]

#Plot
PlotPy(TICKER, PERIOD, INTERVAL)

strategy(signal_value, sentiment_filter)